version: '3.8'

services:
  rest:
    image: charging-station-task
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  db:
    image: 'mysql:8.0'
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_TCP_PORT: 3306